version: "3.3"

services:
  percona-backup:
    build: .
    image: vagabondan/xtrabackup
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /storage/mysql-server/datadir:/var/lib/mysql:rw
      - ./backup:/backups:rw
      - ./backup/crontab:/etc/crontabs/crontab:ro
    networks:
      - percona
  
networks:
  percona: