version: "3.3"

services:
  percona-backup:
    build: .
    image: vagabondan/xtrabackup
    restart: unless-stopped
    volumes:
        # set date and timezone equals to host
      - /etc/localtime:/etc/localtime:ro
        # mysql data dir
      - /storage/mysql-server/datadir:/var/lib/mysql:rw
        # /backups - folder inside container where backup files and logs are written to
      - ./backups:/backups:rw
        # map your crontab to /etc/crontabs/crontab inside container
      - ./backups/crontab:/etc/crontabs/crontab:ro
    networks:
      - percona
  
networks:
  percona: